name: Test toolkit
on: push
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
      - name: Show Golang version
        run: go version
      - name: Tidy module
        run: go mod tidy
      - name: Run tests
        run: go test ./... -v
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
      - name: Show Golang version
        run: go version
      - name: Tidy module
        run: go mod tidy
      - name: Run tests
        run: go test ./... -v
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'
      - name: Show Golang version
        run: go version
      - name: Tidy module
        run: go mod tidy
      - name: Run tests
        run: go test ./... -v
